ANNO:
  PARSER: 'labelimg'
  CREATOR: 'yolov5'
LABELIMG:
  SRC_DIR: 'tests/labelimg_2_yolov5/data-labelimg/'
  IMG_EXTENSION: '.png'
  ANNO_EXTENSION: '.xml'
YOLOV5:
  DST_DIR: 'tests/labelimg_2_yolov5/data-yolov5/'
  IMG_EXTENSION: '.png'
  ANNO_EXTENSION: '.txt'