ANNO:
  PARSER: 'visdrone'
  CREATOR: 'tlt'
VISDRONE:
  SRC_DIR: 'tests/visdrone_2_tlt/data-virdrone/'
  IMG_EXTENSION: '.jpg'
  ANNO_EXTENSION: '.txt'
TLT:
  DST_DIR: 'tests/visdrone_2_tlt/data-tlt/'
  IMG_EXTENSION: '.jpg'
  ANNO_EXTENSION: '.txt'